### ISSUE TITLE
moving the chat still not working

### ISSUE THREAD

**Issue by timoPaF** [Kopatch/TFSCO#7]
Hi,

Great plugin, everything working so far, expect the maybe most important feature of moving the actual chat frame. 

i get following error, which might be related:

`content.js:189 Uncaught TypeError: Failed to execute 'insertBefore' on 'Node': parameter 1 is not of type 'Node'.
    at onExitFullscreen (content.js:189)
    at content.js:47`

this points to:

`    var main = document.querySelector('main');
    main.parentNode.insertBefore(rightCol, main.nextSibling);`

**Comment by Kopatch** [comment]
Hey, thank you for reporting.
Does it happen to you on live channels or VODs?
